# Generated by Django 3.2.5 on 2021-11-14 14:29

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, unique=True, verbose_name='ФИО')),
                ('position', models.CharField(choices=[('GenDir', 'GenDirector'), ('Dir', 'Director'), ('Top', 'TopManager'), ('Manager', 'Manager'), ('Employee', 'Employee')], default=None, max_length=10, verbose_name='Должность')),
                ('salary', models.IntegerField(verbose_name='Заработная плата')),
                ('date_of_employment', models.DateField(default=False, verbose_name='Дата устройства на работу')),
                ('information_on_salary', models.IntegerField(verbose_name='Информация о вылпаченной заработной плате')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.employee', verbose_name='Начальник')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
